project_id = "lhufqnokmdqkvzcxqwkl"

[functions.mosque-admin]
verify_jwt = false

[functions.mosque-photos]
verify_jwt = false
[functions.mosque-donation]
verify_jwt = false

[functions.prayer-change-watch]
verify_jwt = false

